# Scalars
scalar Date
scalar JSON

# Boilerplate
type Info {
  id: ID!
  name: String!
  description: String
}

type EntityPresentationInfo {
  id: ID!
  entityScenario: String
  entityTypeDisplayHint: String
  entityTypeHint: String
}

type Image {
  id: ID!
  height: Int
  width: Int
  hostPageUrl: String
  name: String
  thumbnailUrl: String
}

type Entity {
  id: ID!
  description: String
  entityPresentationInfo: EntityPresentationInfo
  image: Image
  name: String
  webSearchUrl: String
}

type Place {
  id: ID!
  _type: String
  address: String
  name: String
  entityPresentationInfo: EntityPresentationInfo
  telephone: String
  url: String
  webSearchUrl: String
}

type EntitiesSearchResult {
  id: ID!
  entities: [Entity]
  places: [Place]
}

# Query Root
type Query {
  # Boilerplate
  info: Info

  extractEntities(text: String): EntitiesSearchResult
}
